# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SlugField(max_length=4096)),
                ('token', models.CharField(max_length=4096)),
                ('label', models.CharField(default='no-label', max_length=4096)),
                ('score', models.FloatField()),
                ('size', models.IntegerField(default=1)),
            ],
        ),
    ]
