# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_content_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentTokenSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=4096)),
                ('source_id', models.SlugField(max_length=4096, unique=True)),
                ('source_description', models.TextField()),
            ],
        ),
    ]
