# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_content_analysis', '0002_sentimenttokensource'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimenttokensource',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimenttokensource',
            name='min_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
